config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books

  resources :users, only: [:edit, :update, :show, :index]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # 1:Nの「N」側にbelongs_toを記述する
  belongs_to :user

  validates :title, presence: true
  #  presence: trueで空の投稿を禁止
  validates :body, presence: true, length: { maximum: 200 }
  # length:{maximum:200}で200文字以下の文字数制限
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_manyでは何をたくさん持っているかを記述（今回ならbook）
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  # ２文字以上２０字以内で制限、uniquenessでnemeに一意性を持たせる。
  validates :introduction, length: { maximum: 50 }
  # 空の投稿は許可するのでpresence: trueは書かない

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/No_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    # （）内の条件のデータの検索と作成を自動的に行うrailsのメソッド。データが存在すればそのデータを返し、なければ新規作成する
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      # ランダムな文字列を生成するRubyのメソッド
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # guest_user?メソッドを作成したことでguest_userが関わるcontrollerやviewへの記述で使い回すことができ、変更も容易に行えるようになる。
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  # ログインが完了していない場合、トップページとアバウトページ以外は入れないようにする。exceptは指定したもの以外は〜する
  before_action :configure_permitted_parameters, if: :devise_controller?
  # 上記記述はdeviseの機能（ユーザー登録やログイン認証など）が利用される前にconfigure_permitted_parametersメソッドが実行される

  # ログイン後の遷移先を指定
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
    # devise_parameter_sanitizer.permitメソッドを使うことでdeviseでnameのデータ保存を許可する
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_books, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def is_matching_books
      book = Book.find(params[:id])
      unless book.user.id == current_user.id
        redirect_to books_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # ゲストログイン機能の実装
  def guest_sign_in
    user = User.guest
    # sign_inメソッドでUser.guestをログイン状態に
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  # guestuserがURLを直接入力してもedit画面に遷移できないようにするメソッド。
  before_action :ensure_guest_user, only: [:edit]

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def index
    @book_new = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books
  end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  # ログインしているユーザーのidとページのparams[:id]が一致しなかった場合、一覧画面に遷移する
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_new.html.erb
<h2>New book</h2>
      <%= form_with model: book_new do |f| %>
        <div class = "form-group">
          <label for = "book_title">Title</label>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class = "form-group">
          <label for = "book_body">Opinion</label>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class = "form-group">
          <%= f.submit 'Create Book', class: 'btn btn-success' %>
        </div>
      <% end %>

app/views/books/_books_index.html.erb
<h2>Books</h2>
      <table class = "table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colapan = "3"></th>
          </tr>
        </thead>
        <tbody>
          <% books. each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title,book %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/error', obj: @book %>
      <%= form_with model: @book,local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to 'Show', book_path(@book) %>
      |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class = "container px-5 px-sm-0">
  <%= render 'layouts/error', obj: @book %>
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/user_info', user: @user %>

      <%= render 'books/book_new', book_new: @book %>
    </div>
    <!--offsetはカラムに空白を作る時に使用-->
    <div class = "col-md-8 offset-md-1">
      <%= render 'books/books_index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id = "notice"></p>
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/user_info', user: @book.user %>
      
      <%= render 'books/book_new', book_new: @book_new %>
    </div>
    <!--offsetはカラムに空白を作る時に使用-->
    <div class = "col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class = "table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(80,80) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title,@book %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to 'Destroy', book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id = "notice"></p>
<div class = "container">
  <div class = "row">
    <h1 class = "px-3 mx-auto">
      Welcome to
      <i class="fa-solid fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id = "notice"></p>
<div class = "container">
  <div class = "row">
    <div class = "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fa-solid fa-book"></i><strong>Bookers</strong>
         !!
      </h1>
      <p>
        In
        <i class="fa-solid fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class = "btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        <div class = "row">
          <%=  link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class = "row">
          <%=  link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<!--変数をobjにすることでbookエラーにもuserエラーにも共通して分かりやすいようにする-->
<% if obj.errors.any? %>
        <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
        <!--pluralize(book.errors.count, "error"でエラーの数に応じて複数形で表示したりしてくれる-->
        <ul>
          <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersNaka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/497b62484c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
          <%=  link_to root_path, class: 'navbar-brand' do %>
              <span>Bookers</span>
          <% end %>
          <!--レスポンシブ対応で画面が小さくなった時にハンバーガーメニューで表示する-->
          <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label="Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
          </button>

          <div class = "navbar-collapse collapse show" id = "navbarNavDropdown" style>
            <ul class = "navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%=  link_to user_path(current_user), class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li>
                  <%=  link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%=  link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%=  link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
                    <i class="fa-solid fa-right-from-bracket"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%=  link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li>
                  <%=  link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%=  link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%=  link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <!--下記はdeviseのヘルパーメソッド。userがログインしていればtrue、ログアウト中であればfalseが返される-->
    </header>
    <!--フラッシュメッセージは全ページに対応させるためにapplication.html.erbに書くのが良い。-->
    <p id="notice"><%= notice %></p>
    <%= yield %>
    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class = "table">
  <tbody>
    <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
  </tbody>
</table>
<% unless user.guest_user? %>
<div class = "row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<p id = "notice"></p>
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/error', obj: @user %>
      <%= form_with model: @user,local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class: 'form-control name' %>
        </div>
        <div class="form-group">
          <%= f.label :Image %>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class: 'form-control introduction' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id = "notice"></p>
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/user_info', user: @user %>
      
      <%= render 'books/book_new', book_new: @book_new %>
    </div>
    <!--offsetはカラムに空白を作る時に使用-->
    <div class = "col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class = "table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colapan = "3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(80,80) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-3">
      <%= render 'users/user_info', user: @user %>

      <%= render 'books/book_new', book_new: @book_new %>
    </div>
    <!--offsetはカラムに空白を作る時に使用-->
    <div class = "col-md-8 offset-md-1">
      <%= render 'books/books_index', books: @books %>
    </div>
  </div>
</div>